// apps/docs/src/components/ui/Card/Card.tsx
import { cn } from "@/lib/cn";
import type { HTMLAttributes } from "react";

export type CardProps = HTMLAttributes<HTMLDivElement>;

export const Card = ({ className, ...props }: CardProps) => (
  <div
    className={cn(
      "rounded-xl border border-[var(--border)] bg-[var(--card)] text-[var(--card-foreground)] shadow-sm",
      className,
    )}
    {...props}
  />
);
Card.displayName = "Card";

// docs/components/ui/card/Card.vue
<script setup lang="ts">
import type { HTMLAttributes } from "vue";
import { cn } from "@/lib/utils";
const props = defineProps<{ class?: HTMLAttributes["class"] }>();
</script>
<template><div :class="cn('rounded-md border border-[#3b3440] bg-[#14121a] text-white', props.class)"><slot /></div></template>
