// apps/docs/src/components/ui/badge.tsx
import type { HTMLAttributes } from "react";
import { cn } from "@/lib/utils";

export const Badge = ({ className, ...props }: HTMLAttributes<HTMLSpanElement>) => <span className={cn("inline-flex items-center rounded-full border border-[color-mix(in_srgb,var(--primary)_35%,transparent)] bg-[color-mix(in_srgb,var(--primary)_10%,transparent)] px-2.5 py-1 font-mono text-[10px] uppercase tracking-[0.16em] text-[var(--primary)]", className)} {...props} />;

// docs/components/ui/badge/Badge.vue
<script setup lang="ts">
import type { HTMLAttributes } from "vue";
import { cn } from "@/lib/utils";
const props = withDefaults(defineProps<{ class?: HTMLAttributes["class"] }>(), { class: "" });
</script>
<template><span :class="cn('inline-flex items-center rounded-full border border-[#32f3e9]/40 bg-[#32f3e9]/10 px-2.5 py-0.5 font-mono text-[10px] uppercase tracking-wider text-[#32f3e9]', props.class)"><slot /></span></template>
